### PR TITLE
runtime actions

### PR DESCRIPTION
**Pull request by jhadobe**
This PR attempts to create a single page from the 20+ `README` files from the original project. They mainly differed in code samples, so I've used the combined code blocks from the `aio-theme` to reduce clutter. 

I've added a blank `index.md` page as a placeholder.

staging: https://adobedocs.github.io/commerce-extensibility/app-development/starter-kit/integration/

### CODE REVIEW

**Comment by jhadobe** [comment]
i still need to add/customize the images.

**Comment by jhadobe** [comment]
`TabsBlock` would benefit from different styling. using an image makes it more obvious that they are interactive, but we would need images for: customer, customer_group, product, stock, etc. i'm also uncertain how difficult the code block files will be to maintain, but i think this makes for a better user experience.

**Comment by jhadobe** [comment]
> Nice job removing redundancy & duplication 👏 Recently we added some more details to our README that could be useful to add more context to this page. In particular this section could be of your interest: [Different types of actions included in the starter kit](https://git.corp.adobe.com/enterprise-integration/starter-kit#different-types-of-actions-included-in-the-starter-kit). The section explains the two main action types used in the starter-kit:
> 
> * [consumer](https://git.corp.adobe.com/enterprise-integration/starter-kit#consumer-action)
> * [event handler](https://git.corp.adobe.com/enterprise-integration/starter-kit#event-handler-action)

Thanks @rojoangel! We will add those sections in a future PR.

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
@rojoangel Can we get an approval on this PR?

**Review by rojoangel — APPROVED** [review]

**Pull request merged**
